# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Poble Lliure - Som Alternativa - Pirates de Catalunya: Front Republicà"
email: contacte@front-republica.cat
description: >- # this means to ignore newlines until "baseurl:"
  Poble Lliure, Som Alternativa i Pirates de Catalunya, com a organitzacions republicanes, que tenen com a objectiu la defensa dels interessos populars, profundament compromeses en la lluita actual pel dret d'autodeterminació i contra la repressió, hem decidit articular una candidatura que permeti presentar batalla també en aquesta convocatòria d'eleccions.
baseurl: "" # the subpath of your site, e.g. /blog
lang: ca_ES
url: "https://front-republica.cat" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: Front_Republica
  card: summary
logo: /img/fr_mini.png

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
